name: Create Booking E2E Test in Prod
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/30 * * * *' # every 30 minutes
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/create_booking_prod.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Report Error
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: '{workflow} has {status_message}'
          notify_when: 'failure'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          mention_users: 'U01SPPUBB41,U01SPPNLRS5'
          mention_users_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}